function out = jobstruct()
out = struct('axNo',[],'runFolder',[],...
                        'xData',[],'yData',[],'zData',[],...
                        'xLab',[],'yLab',[],'zLab',[],...
                        'xLimits',limitstruct(),'yLimits',limitstruct(),'zLimits',limitstruct(),...
                        'legendText','series0','legendLocation','northeast',...
                        'bestFitActive',0,'bestFitLine',createLineSpec(),...
                        'line',createLineSpec(),...
                        'suffix','ldnum_0');
end