function [E,S] = ImportAverageStressStrainFile(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [E11,E12,E22,S11,S12,S22] = IMPORTFILE(FILENAME) Reads data from text
%   file FILENAME for the default selection.
%
%   [E11,E12,E22,S11,S12,S22] = IMPORTFILE(FILENAME, STARTROW, ENDROW)
%   Reads data from rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   [E11,E12,E22,S11,S12,S22] = importfile('RVE0SVE0LC0.out',4, 4);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2019/03/14 14:12:03

%% Initialize variables.
delimiter = ' ';
if nargin<=2
    startRow = 4;
    endRow = inf;
end

%% Format for each line of text:
%   column3: text (%s)
%	column4: text (%s)
%   column5: text (%s)
%	column6: text (%s)
%   column7: text (%s)
%	column8: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%*s%*s%s%s%s%s%s%f%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%*s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'MultipleDelimsAsOne', true, 'TextType', 'string', 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'MultipleDelimsAsOne', true, 'TextType', 'string', 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

E11 = str2double(dataArray{:, 1});
E12 = str2double(dataArray{:, 2});
E22 = str2double(dataArray{:, 3});
S11 = str2double(dataArray{:, 4});
S12 = str2double(dataArray{:, 5});
S22 = (dataArray{:, 6});

E = [E11;E22;E12];
S = [S11;S22;S12];


